# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
        master:
            - step:
                name: Build
                script:
                  - npm install && npm run build
                artifacts:
                  - build/**
            - step:
                name: 'Deploying to Firebase'
                caches:
                  - node
                script: # Modify the commands below to build your repository.
                  - pipe: atlassian/firebase-deploy:0.3.5
                    variables:
                        FIREBASE_TOKEN: $FIREBASE_TOKEN
                        PROJECT_ID: $FIREBASE_PROJECT_ID
                        MESSAGE: 'Deploying TorontoLife'
    
